<?php 
	function cabecera() {
		echo '
        	<div class="contenedor">
            <h1 class="icon-hospital">Hospital Arcángeles</h1>
            <input type="checkbox" id="menu-bar">
            <label class="icon-menu-outline" for="menu-bar"></label>
            <nav class="menu">
                <a href="">Inicio</a>
                <a href="">Nosotros</a>
                <a href="">Contacto</a>
                <a href="">Departamentos</a>
                <a href="">Citas</a>
            </nav>
       		</div>
		';
	}
    function pie() {
        echo '
          <div class="contenedor">
              <p class="copy">Hospital Arcángeles &copy; 2019</p>
              <div class="sociales">
                  <a class="icon-gplus-squared" chref=""></a>
                  <a class="icon-linkedin-1"href=""></a>
                  <a class="icon-mail-alt" href=""></a>
                  <a class="icon-twitter-squared" href=""></a>
              </div>
          </div>
        ';
    }
?>